### ISSUE TITLE
Error while building docker container

### ISSUE THREAD

**Issue by sdecesco** [OptiMaL-PSE-Lab/DeepDock#1]
Hi, 

I've tried to build the docker container and I get this error :

`Step 22/26 : RUN ["wget", "-O", "reduce.gz", "http://kinemage.biochem.duke.edu/php/downlode-3.php?filename=/../downloads/software/reduce31/reduce.3.23.130521.linuxi386.gz"]`
` ---> Running in d2006b089496`
`--2021-12-07 13:27:22--  http://kinemage.biochem.duke.edu/php/downlode-3.php?filename=/../downloads/software/reduce31/reduce.3.23.130521.linuxi386.gz
Resolving kinemage.biochem.duke.edu (kinemage.biochem.duke.edu)... 40.76.186.240`
`Connecting to kinemage.biochem.duke.edu (kinemage.biochem.duke.edu)|40.76.186.240|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-07 13:27:22 ERROR 404: Not Found.`

`The command 'wget -O reduce.gz http://kinemage.biochem.duke.edu/php/downlode-3.php?filename=/../downloads/software/reduce31/reduce.3.23.130521.linuxi386.gz' returned a non-zero code: 8
`
Looking forward to test deepdock ^^ 

S

**Comment by Chengpromise** [comment]
Thanks, I have the same issue. Looking forward to the reply

**Comment by htreutlein1** [comment]
I also have the same issue :-(  Also there are lot of issues when I try to install from Source.

**Comment by SJTUMisaka** [comment]
Same issue

**Comment by cmielke-vir** [comment]
Hey all, I fixed this in my fork : https://github.com/cmielke-vir/DeepDock

In short, the lab that built reduce appears to be making changes to their website, so the download link is stale. In my version of the dockerfile, I replaced it with a git pull and compilation step of reduce.

Note, I still haven't gotten the full pipeline working, and there are other modifications I made to the dockerfile that might not be advisable.

**Comment by htreutlein1** [comment]
Thank you very much cmielke-vir for making your fork available.  I now could create the docker image.  I haven't run the examples and tests yet.

**Comment by omendezlucio** [comment]
Hi, I also updated the Dockerfile in this repo and added a Docker image that can be pulled from this [docker repo](https://hub.docker.com/r/omendezlucio/deepdock): 
`docker pull omendezlucio/deepdock`
