### ISSUE TITLE
About screening power calculation 

### ISSUE THREAD

**Issue by ChifengWoo** [OptiMaL-PSE-Lab/DeepDock#2]
Your article "https://www.nature.com/articles/s42256-021-00409-9" is great, thank you very much for sharing the source code and test results. But I have some questions about the results of the CASF2016 Screening power test.
  In your ForwardScreeningPower_Deepdocks_3A.out:
The best ligand is found among top 1% candidates for 25 cluster(s); success rate = 43.9%
The best ligand is found among top 5% candidates for 35 cluster(s); success rate = 61.4%
The best ligand is found among top 10% candidates for 47 cluster(s); success rate = 82.5%
 
  Why do the results have a different number of clusters instead of a uniform 57 clusters？
  Looking forward to your reply, thanks!

**Comment by omendezlucio** [comment]
Hi @ChifengWoo:

Thanks for your interest and for your question. All the results were calculated on 57 but the lines you mention are the ones for which the ligand was found top candidates. For example:

> The best ligand is found among top 1% candidates for 25 cluster(s); success rate = 43.9%

**Interpretation**: after running the test on the 57 clusters only in 25 of them we found the ligand among the top 1% candidates. This gives a success rate of 43.9% ( from (25/57)* 100).

Hope this makes it clearer.
